version: '3.3'
services:
    pms-docker:
        ports:
            - 80:80
            - 32400:32400/tcp
            - 3005:3005/tcp
            - 8324:8324/tcp
            - 32469:32469/tcp
            - 1900:1900/udp
            - 32410:32410/udp
            - 32412:32412/udp
            - 32413:32413/udp
            - 32414:32414/udp
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./mnt/plex-config:/config #example
            - ./mnt/plex-transcode:/transcode #example
            - ./mnt/plex:/data #example
            - ./mnt/music:/data2 #example
        restart: always
        logging:
            options:
                max-size: 1g
        container_name: plex
        environment:
            - TZ=America/Detroit
            - PLEX_CLAIM=""
            - ADVERTISE_IP=http://0.0.0.0:32400/
        image: plexinc/pms-docker