version: '3.3'
services:
    godaddy-ddns:
        container_name: ddns
        restart: always
        environment:
            - GODADDY_KEY=<YOUR_KEY>
            - GODADDY_SECRET=<YOUR_SECRET>
            - GODADDY_DOMAIN=mydomain.com
        image: peteward44/godaddy-ddns